#!/bin/bash
cd "$(dirname "$0")"
source ./aqua/env/openresty_setenv
luajit aqua/web/nginx/compile.lua

export DYLD_FALLBACK_LIBRARY_PATH=$PWD/bin/mac64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/bin/linux64

if [[ $1 == "start" ]]; then
	openresty -p $(pwd) -c nginx.conf
elif [[ $1 == "stop" ]]; then
	openresty -p $(pwd) -c nginx.conf -s stop
elif [[ $1 == "reload" ]]; then
	openresty -p $(pwd) -c nginx.conf -s reload
fi
