#!/bin/bash

LUA_ROOT=$HOME/lua
OR_ROOT=/opt/openresty

LUA_PATH="$LUA_PATH;$PWD/?.lua;$PWD/?/init.lua"

PATH=$OR_ROOT/bin:$PATH
PATH=$OR_ROOT/luajit/bin:$PATH
PATH=$LUA_ROOT/tree/bin:$PATH

LUA_PATH="$LUA_PATH;$LUA_ROOT/share/?.lua;$LUA_ROOT/share/?/init.lua"
LUA_PATH="$LUA_PATH;$LUA_ROOT/tree/share/lua/5.1/?.lua;$LUA_ROOT/tree/share/lua/5.1/?/init.lua"
LUA_CPATH="$LUA_CPATH;$LUA_ROOT/tree/lib/lua/5.1/?.so"

LUA_PATH="$LUA_PATH;$OR_ROOT/lua/?.lua;$OR_ROOT/lua/?/init.lua"
LUA_CPATH="$LUA_CPATH;$OR_ROOT/lualib/?.so;$OR_ROOT/?.so;$OR_ROOT/loadall.so"

LUA_PATH="$LUA_PATH;$OR_ROOT/lualib/?.lua;$OR_ROOT/lualib/?/init.lua"

LUAROCKS="luarocks --lua-version 5.1 --lua-dir /opt/openresty/luajit --tree $LUA_ROOT/tree"

export PATH
export LUA_PATH
export LUA_CPATH
