#!/bin/bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:$PWD/bin/linux64
LOVE2D_NAME=$(curl --silent "https://api.github.com/repos/love2d/love/releases/latest" | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' | grep -i .AppImage)
NAME_OF_THE_NEW_VERSION=$(curl --silent "https://api.github.com/repos/love2d/love/releases/latest" | grep '"browser_download_url":' | sed -E 's/.*"([^"]+)".*/\1/' | grep -i .AppImage)
CHECK_IF_EXISTS=$(ls | grep -i .AppImage)
echo $CHECK_IF_EXISTS


REQUIRED_PKG="libcurl4-openssl-dev ffmpeg libavcodec-dev libavformat-dev libswscale-dev"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
echo Checking for $REQUIRED_PKG: $PKG_OK
if [ "" = "$PKG_OK" ]; then
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  sudo apt-get --yes install $REQUIRED_PKG
fi




if [ -f "$LOVE2D_NAME" ]; then
	echo "File exists"
	./$LOVE2D_NAME .
else
	if [[ $CHECK_IF_EXISTS != "" ]]; then
		echo "New version found. Download it? (y/n)"
		read NEW_VERSION
		echo $NEW_VERSION
		if [[ $NEW_VERSION == "y" ]]; then
			rm $CHECK_IF_EXISTS
			until wget $NAME_OF_THE_NEW_VERSION
			do
				sleep 5
			done
			clear
			./$LOVE2D_NAME "."
		else
			./$CHECK_IF_EXISTS "."
		fi
	else
		echo "File does not exist"
		until wget $NAME_OF_THE_NEW_VERSION
		do
			sleep 5
		done
		clear
		./$LOVE2D_NAME "."
	fi
fi
