require("CloudburstEngine")
require("StateManager")
require("BackgroundManager")
require("FileManager")
require("MapList")
require("List")
require("Cache")
require("KeyBindManager")
require("PlayField")
require("InputModeLoader")
require("Core")
require("Group")
require("NoteSkinManager")
require("CLI")
require("Editor")

core = Core:new()
core:activate()
