require("CloudburstEngine")
require("StateManager")
require("BackgroundManager")
require("FileManager")
require("MapList")
require("List")
require("Cache")
require("KeyBindManager")
require("PlayField")
require("InputModeLoader")
require("NoteSkinLoader")
require("Core")

core = Core:new()
core:activate()
