return {
	editorController = {
		"selectModel",
		"editorModel",
		"noteSkinModel",
		"previewModel",
		"configModel",
		"resourceModel",
		"windowModel",
		"cacheModel",
		"fileFinder",
	},
	fastplayController = {
		"rhythmModel",
		"replayModel",
		"cacheModel",
		"playContext",
	},
	gameplayController = {
		"rhythmModel",
		"selectModel",
		"noteSkinModel",
		"configModel",
		"difficultyModel",
		"replayModel",
		"multiplayerModel",
		"previewModel",
		"discordModel",
		"chartRepo",
		"onlineModel",
		"resourceModel",
		"windowModel",
		"notificationModel",
		"speedModel",
		"cacheModel",
		"fileFinder",
		"playContext",
		"pauseModel",
	},
	multiplayerController = {
		"multiplayerModel",
		"configModel",
		"selectModel",
		"playContext",
	},
	resultController = {
		"selectModel",
		"replayModel",
		"rhythmModel",
		"onlineModel",
		"configModel",
		"fastplayController",
		"playContext",
	},
	selectController = {
		"selectModel",
		"previewModel",
		"modifierSelectModel",
		"noteSkinModel",
		"configModel",
		"backgroundModel",
		"multiplayerModel",
		"onlineModel",
		"cacheModel",
		"osudirectModel",
		"windowModel",
		"playContext",
	},
}
