return {
	collapse = true,
	collection = "",
	noteChartDataEntryId = 1,
	noteChartEntryId = 1,
	noteChartSetEntryId = 1,
	scoreEntryId = 1,
	searchMode = "filter",
	judgements = "soundsphere",
	scoreFilterName = "No filter",
	filterName = "No filter",
	filterString = "",
	lampString = "",
	sortFunction = "title",
}
