ALTER TABLE scores RENAME TO temp;
CREATE TABLE IF NOT EXISTS `scores` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`noteChartHash` TEXT NOT NULL,
	`noteChartIndex` REAL NOT NULL,
	`isTop` INTEGER DEFAULT FALSE,
	`playerName` TEXT,
	`time` INTEGER,
	`accuracy` REAL,
	`maxCombo` INTEGER,
	`modifiers` TEXT,
	`replayHash` TEXT,
	`pauses` REAL,
	`ratio` REAL,
	`perfect` REAL,
	`notPerfect` REAL,
	`missCount` REAL,
	`mean` REAL,
	`earlylate` REAL,
	`inputMode` TEXT,
	`timeRate` REAL,
	`difficulty` REAL,
	`pausesCount` REAL
);
INSERT INTO scores(
	`id`,
	`noteChartHash`,
	`noteChartIndex`,
	`playerName`,
	`time`,
	`accuracy`,
	`maxCombo`,
	`modifiers`,
	`replayHash`,
	`pauses`,
	`ratio`,
	`perfect`,
	`notPerfect`,
	`missCount`,
	`mean`,
	`earlylate`,
	`inputMode`,
	`timeRate`,
	`difficulty`,
	`pausesCount`,
	`isTop`
)
SELECT
	`id`,
	`noteChartHash`,
	`noteChartIndex`,
	`playerName`,
	`time`,
	`accuracy`,
	`maxCombo`,
	`modifiers`,
	`replayHash`,
	`pauses`,
	`ratio`,
	`perfect`,
	`notPerfect`,
	`missCount`,
	`mean`,
	`earlylate`,
	`inputMode`,
	`timeRate`,
	`difficulty`,
	`pausesCount`,
	0
FROM temp;
DROP TABLE temp;
