DROP TABLE IF EXISTS temp;
ALTER TABLE scores RENAME TO temp;
CREATE TABLE IF NOT EXISTS `scores` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`chart_hash` TEXT NOT NULL,
	`chart_index` REAL NOT NULL,
	`is_top` REAL DEFAULT 0,
	`time` REAL,
	`accuracy` REAL,
	`max_combo` REAL,
	`modifiers` TEXT,
	`rate` REAL,
	`const` REAL,
	`replay_hash` TEXT,
	`ratio` REAL,
	`perfect` REAL,
	`not_perfect` REAL,
	`miss` REAL,
	`mean` REAL,
	`earlylate` REAL,
	`inputmode` TEXT,
	`difficulty` REAL,
	`pauses` REAL
);
INSERT INTO scores(
	`id`,
	`chart_hash`,
	`chart_index`,
	`is_top`,
	`time`,
	`accuracy`,
	`max_combo`,
	`modifiers`,
	`rate`,
	`const`,
	`replay_hash`,
	`ratio`,
	`perfect`,
	`not_perfect`,
	`miss`,
	`mean`,
	`earlylate`,
	`inputmode`,
	`difficulty`,
	`pauses`
)
SELECT
	`id`,
	`noteChartHash`,
	`noteChartIndex`,
	`isTop`,
	`time`,
	`accuracy`,
	`maxCombo`,
	`modifiers`,
	`timeRate`,
	0,
	`replayHash`,
	`ratio`,
	`perfect`,
	`notPerfect`,
	`missCount`,
	`mean`,
	`earlylate`,
	`inputMode`,
	`difficulty`,
	`pausesCount`
FROM temp;
DROP TABLE temp;
