---@class yi.Commands
local Commands = {
	PUSH_STATE = 1,
	POP_STATE = 2,
	SET_COLOR = 10,
	SET_BLEND_MODE = 11,
	APPLY_TRANSFORM = 12,
	DRAW_DROP_SHADOW = 20,
	DRAW_BACKGROUND_LAYER = 21,
	DRAW_VIEW = 22,
	DRAW_OUTLINE = 23,
	STENCIL_START = 30,
	STENCIL_END = 31
}

return Commands
